### ISSUE TITLE
Level 1: When you start level 1 through the Main Menu scene, you start with no items in your inventory

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#100]
** Describe the bug **
If you start from the Main menu Unity Scene and choose Level1, you spawn in the scene with no items in your inventory. When you start in the Level 1 Unity Scene, you start with all the rocks and clay you need.

** Version **
mainV4.17

** Screenshots **
Having started from the Main Menu Scene:
<img width="613" alt="from main menu loading" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/182d0482-bbd9-4fa4-b865-6fbb4d5f588c">

Having started from the Level 1 Scene:
<img width="583" alt="from level 1 loading" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/4c201193-3b41-4fba-a6a3-1a71d774a799">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
resolved part of another issues
