### ISSUE TITLE
Level 1: The tokens indicating which material is needed is inside of all repairable objects

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#101]
** Describe the bug **
When you try to fix the pots, stairs and piles of rubble, the token that shows what Item you need for it is in the model or in the floor

** Version **
mainV4.17

** Screenshots **
Token in the pot:
<img width="897" alt="token in pot" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/467e729e-6626-48de-a161-0a2486acc440">

Token in the Stairs:
<img width="576" alt="token in stairs" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/a2383a66-96e2-4129-9fdb-03ad5764dfbc">

Token in the Rubble:
<img width="1116" alt="token in rubble" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/ce14901f-2a5f-4d4e-9321-7fb0836cec49">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
has been reset this is an issues for all repairable need to be mainule updated

**Comment by Xeleolon** [comment]
this shouldn't be a problem for this item as the player should have the items this is connected to an early issues
