### ISSUE TITLE
Level 1: You can force your way onto pot and stair colliders by jumping

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#102]
** Describe the bug **
If you hold jump and move forwards facing pots and stone stairs, you can force your way ontop of their collider and then use that to get up the stairs without fixing anything. Getting on the stairs takes 2 jumps for some reason, since the first doesn’t make it but the second does.

I mean, this can be a feature if we want. It's not a big problem, and fixing everything is still required to finish the level anyway.

** Version **
mainV4.17

** Screenshots **
Standing on broken staircase after jumping on it:
<img width="872" alt="standing on staircase" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/1aa4b7f3-24ce-4795-a46f-5d0d85d2ae70">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
increased hieght on pots collider to prevent this
