### ISSUE TITLE
Level 1: You start with the Yellow staff in your hand, but it switches to the blue hammer when you press 1

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#103]
** Describe the bug **
When you spawn in, the character is holding the yellow tool. Then when you follow the tutorial and press 1, the model switches to the hammer (which currently is the "Repair Mode".

Linked with another bug about the tools having the wrong models.

Could still happen with different models even if the models are switched to the correct ones.

** Version **
mainV4.17

** Screenshots **
Starting out:
<img width="1078" alt="you start with repair" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/930bb6ae-fc9c-4d80-bdb6-782f921aa874">

Having pressed 1 to get repair tool:
<img width="1065" alt="then you press 1 and get the replenish hammer" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/48613a7d-e406-4458-922e-a2eb209ed953">

** Desktop System **
Windows 10

**Comment by DefinitelyACat** [comment]
Update: You start with the yellow staff in your hand in all levels. I'm unsure which "tool mode" you start out in, though, as currently the issue of the models being mixed up is still present. We'll see what happens when the models are correctly placed.

**Comment by Xeleolon** [comment]
Fixed
