### ISSUE TITLE
All Levels: There is No way to test Shake animation

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#107]
** Describe the bug **
There is no Interactible tag to test if shaking script works. Even after making one to give an object, the object did not shake. Not sure what's gone wrong here.

** Version **
mainV4.17

** Screenshots **
Proof of all Tags:
<img width="172" alt="there is no Interactible tag" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/19919d1a-0c24-46d8-90d6-bedb89f4c03c">

** Desktop System **
Windows 10

**Comment by DefinitelyACat** [comment]
Yeah, I messed up by accidentally hitting enter when I'd typed "All Levels:" (and that's it) in the title. That somehow caused the issue to be logged with just that title and no other information, so I edited it a few times to add all I needed to...

**Comment by Xeleolon** [comment]
Wied this isn't an issues for me current the only non shakeable is in test scene

**Comment by Xeleolon** [comment]
some of the issues is due to changes only being on the copy of the testing version of thep player vs the prefab

**Comment by Xeleolon** [comment]
resolved issues
