### ISSUE TITLE
Levels 3+: When holding no tool, both tool icons are lit up

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#108]
** Describe the bug **
When holding no tool, both the yellow and red icon are fully coloured instead of being duller like they should be in the bottom right.

** Version **
mainV4.17

** Screenshots **
Holding No Tool, with both icons lit up:
<img width="1111" alt="When holding nothing other icons are bright" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/6207e93e-a901-42a0-b73b-81b56c3d8bc9">

Holding Repair and it being lit up while destroy is dull:
<img width="211" alt="Holding repair" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/5de74144-4f54-44ec-bffb-df0db7ca24f8">

Holding Destroy and it being lit up while repair is dull:
<img width="194" alt="Holding destroy" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/82f5fcb0-823e-4238-a0dc-369910927d93">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
this is the bomb mode no ui set up yet

**Comment by Xeleolon** [comment]
bomb ui set up
