### ISSUE TITLE
Levels 3+: Can't replenish while holding no tool

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#109]
** Describe the bug **
When not holding any tool (Mode 3, where you would have hands out), can't interact with objects to replenish them. Must be holding either repair or destroy.

I don't know whether this is on purpose, though. If it's meant to be like that, apply the misunderstanding tag and close this.

** Version **
mainV4.17

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
may not be an issues will need to recheck after bomb ui implented.

**Comment by Xeleolon** [comment]
updated bomb ui no problem with this now
