### ISSUE TITLE
Level 3: Can't finish the level

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#110]
** Describe the bug **
The finishing barrier in level 3 doesn't work. I can run right through the area behind the door and there's no change.
It doesn't matter if you've loaded straight into the scene or from the main menu.

** Version **
mainV4.17

** Screenshots **
Standing in space where Finish Barrier should activate:
<img width="1082" alt="Can't finish level" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/ec356d12-a43f-4e4f-9b00-18a6b2a046e0">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
issues with update to collision script will fix

**Comment by Xeleolon** [comment]
fixed
