### ISSUE TITLE
Level 4: Can't interact with anything if looking down at a certain angle.

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#113]
** Describe the bug **
As title says, if you look down at an angle at an object you can interact with (destroy, repair or replenish)

** Version **
mainV4.17

** Screenshots **
Can't interact with chest like this:
<img width="1106" alt="Can't interact with chest here" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/1380f79a-d603-4f53-8c61-4dc55ded4165">

But can like this:
<img width="1104" alt="Can interact with chest here" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/e8643280-0a23-4ea2-8411-21b39384abd6">

Can't interact with rubble like this:
<img width="1105" alt="can't interact with rubble here" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/813a3e47-ad7c-4dee-a136-6c9166a6c699">

But can like this:
<img width="1105" alt="can interact with rubble here" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/fb5525d8-1387-40a4-8f4e-7b7b0c774d10">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
should be fixed now issues possible due to gremlin skin not being asigned to the player layer

**Comment by Xeleolon** [comment]
Fixed
