### ISSUE TITLE
General Bug: If you try to replenish mid-jump, player starts sliding a direction

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#114]
** Describe the bug **
If you're jumping and then click to interact with something that you can replenish, while the UI menu is up, the player slides along the ground until you exit the menu.

** Version **
mainV4.17

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
oh that when they that get caused was wondering why that didn't allways happen

**Comment by Xeleolon** [comment]
complete paused player movement entirely
