### ISSUE TITLE
Multiple Level 5 bugs (Level is unfinished at this point, so some might get fixed via normal development)

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#115]
** Describe the bugs and give screenshots**

Bug 1:
You don’t get anything from the bomb pile. The pile disappears and reappears as though it’s restocking itself, but you don’t have an item or a tool or anything.
<img width="1097" alt="nothing from bomb" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/2792c1cc-d79c-4a0a-9e44-7e376e026848">

Bug 2:
The text at the start of the level is the text from level 2 (Introducing Destroy in The Cave)
<img width="1091" alt="text is same" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/0b5c52ad-1ada-4e2e-b07e-1feb68199b36">

Bug 3:
Drawbridge doesn't have a "Floor” Label, so the player slides around on it and can’t jump while on it.
<img width="424" alt="bridge layer" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/3578d7e0-52d7-4bba-be52-315c047a5337">

Bug 4:
Things clip through the floors because they're planes.
<img width="221" alt="box clipping through floor" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/17743872-0f4d-4e3e-bcf3-c174ae143e2e">
<img width="1076" alt="stones clipping through floor" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/f0352c33-d777-458b-a625-8cf3c250cca1">

Bug 5:
You can scale (climb up) the mountains around you and just jump off if you want to.
<img width="1099" alt="can just get out of level and jump down" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/63a1b4af-4e39-452b-8ae4-f8cea3fe0fc4">

Bug 6:
You don't die when you fall down the pit
<img width="1093" alt="don't die on falling down cliff" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/78dcccb2-c8c8-437d-95c8-20f845e25271">

Bug 7:
This one tile on all visible floors is the wrong orientation. It's harder to see on the stone brick floor, but it's there. The tile exactly opposite it on each floor is the same.
<img width="548" alt="harder to see on the stones" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/128f888e-4274-4e0a-a1e5-32893a050365">
<img width="932" alt="This one is the wrong way" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/226b842a-dca1-4ce8-91b6-2341205fc046">
<img width="857" alt="Same on the second floor" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/505a9fba-7f5d-491d-9e7f-3b9ef1d63a23">

** Version **
mainV4.17

** Desktop System **
Windows 10

**Comment by DefinitelyACat** [comment]
I fixed the draw bridge easy enough. It'll be in the BugFixesFromV4.17 Branch.

**Comment by Xeleolon** [comment]
tille wrong orretian due to angle floor being wired
