### ISSUE TITLE
General Issue: Crate Model should be changed back to Crate with no removeable lid

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#116]
** Describe the bug **
The crates are currently the model with a removeable top, but we don't ever remove it. That version doesn't have a texture, so switching the model back to the original crate would be best. Updating the prefab should fix the issue with all levels, as all are based from the prefab.

** Version **
mainV4.66

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
completed
