### ISSUE TITLE
Potion Level: Chest that gives you a key should be a crate

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#117]
** Describe the bug **
Potion level that has a chest behind the collapsed wall that gives you a key. This model should be a crate, not a chest.

** Version **
mainV4.67

** Screenshots **
<img width="1134" alt="chest should be crate" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/74fa6aeb-f392-45d5-80f4-8848a42777e3">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
team agreed to keep chest for potion but moved the chest forward so I wasn't clipping the wall
