### ISSUE TITLE
Catapult Level: Slime texture isn't showing as green

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#118]
** Describe the bug **
The 3D slime texture is set to be too transparent and isn't presenting as green currently

** Version **
mainV4.67

** Screenshots **
<img width="576" alt="image" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/85af1308-90a0-4548-af5d-de157cf678db">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
improved the greenishness of the slimes
