### ISSUE TITLE
Cave-In Level (Level 2): Small rocks on floor have colliders and shouldn't 

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#120]
** Describe the bug **
The small rocks on the floor before the Rubble you must destroy in the cave-in level have colliders and provide an annoying little bump that isn't needed.

** Version **
mainV4.66

** Screenshots **
<img width="957" alt="image" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/5871edd8-4436-4250-b8bf-a9a01284f6ba">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
fixed
