### ISSUE TITLE
Potion Level: Rocks that stop you from skipping maze are missing

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#121]
** Describe the bug **
Rock Blockage to stop skipping past the maze is missing. Needs to be replaced with new blockage Nathan wanted to do.

** Version **
mainV4.67

** Screenshots **
<img width="1502" alt="image" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/f0a59cc6-2dcf-441c-bf88-802f58727206">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
back in now
