### ISSUE TITLE
Final Door open

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#14]
** Describe the bug **
Currently, the final door can be opened before gas is disarmed

** Version **
mainV051

** To Reproduce **
Go up to the final door and click to unlock it, then walk through, while gas trap is still active.

** Expected behavior**
Door should be locked until gas trap is disarmed and other tasks are completed.

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
No Current fix can be made till next semester, as I need to do an overall for the doors anyway with a load of new features, like being able only to work after center tasks are completed, closing the doors being available, animation of door opening which can't be added currently will add it as a new feature for next semester to implentent

**Comment by Xeleolon** [comment]
Also can't make a simple fix with the door key ontop of any other object as only one interactable for each object may need to develop an object which can door more than one function

**Comment by DefinitelyACat** [comment]
Having thought about it some more, we can leave this in. Since this is a bit of a job simulator, we could have it where _at minimum_, the player needs to complete 50% of the tasklist stuff, but can leave as soon as that is done. They'll just get more points and stuff the more they complete. 100% completion would maybe have an extra bonus.

**Comment by Xeleolon** [comment]
Resolved issues by overhalling door system entire and upgrading it to allow for item to be added before door will open
