### ISSUE TITLE
Player slides too far when stopping their own movement

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#48]
** Describe the bug **
When you stop holding a movement button, the player slides too far. Either we need no slide, or only the slightest bit.
(removing entirely might also fix the stair slide bug)

** Version **
mainV2.30

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
this can be altered by ajust how much drag need to comfirm this the correct amount with team

**Comment by Xeleolon** [comment]
Isaish please check current version and play with the drag control in player to find correct version

**Comment by Xeleolon** [comment]
Check and fixed
