### ISSUE TITLE
Objects becoming the wrong thing when fixed

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#49]
** Describe the bug **
Some objects aren't replaced with the properly fixed version when "repaired". Some aren't the right model, one isn't textured. 

** Version **
mainV2.38

** Screenshots **
On level 1, some pots are their fully made but still 'broken' variant when repaired.
<img width="548" alt="pot still broke" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/749b722b-8cdc-4e5c-bf7f-5e8acb8ffbfc">

On level 1, the bookshelf stays yellow when you fix it.
<img width="407" alt="bookshelf still yellow" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/9628a4de-aa8a-49b4-8f06-1440b568af4e">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
new feature added to the repair broke the pot. update them to dispearm and update the bookshelf so it temp model has a full fived model to go with it
