### ISSUE TITLE
Can't interact with catapults in level2

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#50]
** Describe the bug **
Items that you pick up and need to put into things are wrong. Rocks on level 2 give the chicken, and the catapults need the skull. Both should be the magic dust or something.

** Version **
mainV2.38

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
Issues left in behind testing creative mode in debug ficed issues now
