### ISSUE TITLE
Can't strafe sideways up stairs

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#52]
** Describe the bug **
When attempting to move sideways up them, you move very slowly as though the stairs are actively fighting you moving up them.
Can be annoying for players who turn before they get to the top of the stairs but keep trying to move to the side up them.

** Version **
mainV.2.41

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
this issues is part of the an early issues about the stairs need to be relogged under that stair

**Comment by DefinitelyACat** [comment]
This issue's contents have been added to a previously logged issue that is also related to movement on stairs. Both are likely to be fixed via the same patch, so this issue will be filed under "duplicate" and "invalid", while being marked as closed.
