### ISSUE TITLE
Player can move camera when in replenish if they've changed scene

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#55]
** Describe the bug **
The only way I've reproduced this is if I play the previous level and get to the end so it loads the next level.
Then if you interact with something to Replenish it, the camera moves with the mouse movement. 

** Version **
mainV3.05

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
due to load level demand player be able to move when loading was complete made it check if it can
