### ISSUE TITLE
Final Level rubble that turns into an archway doesn't disappear

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#57]
** Describe the bug **
After fixing the stairs in Final Level, the rubble you turn into an archway doesn't go away.

** Version **
mainV3.05

** Screenshots **
<img width="809" alt="rocks don't go away" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/3909000c-f4f1-4232-a42f-30795fa368eb">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
removed this intirely
