### ISSUE TITLE
Can get partially under the table, but jumping then pushes you away.

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#60]
** Describe the bug **
If you move close enough to the side of the table that's open underneath, the top round part of the player's capsule collider can let you get underneath the table a little bit. If you then jump, you get flung up and a little back. This is probably because the collider is sliding against the bottom of the table.

** Version **
mainV3.05

** Screenshots **
N/A

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
what do you expect to happen?

**Comment by DefinitelyACat** [comment]
Nathan has updated colliders.
