### ISSUE TITLE
The one torch in the dead end down stairs doesn't have a light

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#61]
** Describe the bug **
In the dead end staircase that goes down from the major hallway after the room with the 4 desks, the torch inside doesn't cast light.

** Version **
mainV3.21

** Screenshots **
<img width="622" alt="One Unlit Torch" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/14d31206-7b7c-437b-a0af-debf2eaa6f7d">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
on purpose as it a dead end didn't want a light source to assist directing the player down this way
