### ISSUE TITLE
Spiney Crate is floating when summoned

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#62]
** Describe the bug **
When you summon the spiney crate, the model is floating.

** Version **
mainV3.21

** Screenshots **
<img width="830" alt="Floating Crate" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/b3448968-0c63-4451-8b02-4631e3bb3299">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
don't you like floating creature crates

**Comment by Xeleolon** [comment]
Team can fix this issues
