### ISSUE TITLE
Key item shows as veritical

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#63]
** Describe the bug **
The keys in the inventory are vertical instead of horizontal

** Version **
mainV3.21

** Screenshots **
<img width="106" alt="Key is vertical" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/ccb4fa9a-2a2a-4d30-acc2-8a4939799bbc">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
issues due to key image being changed with new rotation that correct and old stuff counting for that fixed the issues and the animation
