### ISSUE TITLE
When the 4 desks in Final Level are fixed, they become blueish

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#64]
** Describe the bug **
When the tables are fixed and the mob remains are chosen, the tables become the wrong texture. Unsure of the cause.

** Version **
mainV3.21

** Screenshots **
<img width="904" alt="When fixed desk change colour" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/7708e185-0be3-4ce4-9212-e4365e641702">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
wrong texture on purpose at the moment waiting for table mat or actuactly kitchen table model to be made

**Comment by Xeleolon** [comment]
Update the desks to have a cloth over them now
