### ISSUE TITLE
Items stack wrong once you get more than 4 different types

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#65]
** Describe the bug **
When you pick up a 5th type of item, it replaces one of the ones you already have.
At some point, I had a bunch of wood, then I grabbed one gold ingot and immediately had the number of wood I had+1 in gold bars instead.

** Version **
mainV3.21

** Screenshots **
<img width="263" alt="due to only having 4 slots, if you get a 5th item, it takes on the number you had of a previous one" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/8e78c19e-1e1b-4cd4-88bf-7aac997fbb4f">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
this is a fault with the level you can't fave more the four item within the level

**Comment by Xeleolon** [comment]
need to check object breaking that produce item not needed removed them giving them odd items
