### ISSUE TITLE
Crate at the end required slimy instead of boney

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#66]
** Describe the bug **
Tried to select the boney out of the options for this last crate, but it only accepted slimey. The crate was still the boney, though.

** Version **
mainV3.21

** Screenshots **
<img width="1052" alt="This one required slimey" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/2e3b0445-4a14-4497-b2df-7f1e6cab1d56">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
fixed this is a small issues could of been fixed by team just wrong item
