### ISSUE TITLE
Levels 1,2&3: Camera and Player can move but tutorial is stuck on screen

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#67]
** Describe the bug **
When in levels 1, 2 and 3, no matter how that level was loaded into, the tutorials stay on the screen. You can move the camera and the player around while this is happening.
In level 1, you have a cursor to start with so you can finish the tutorial by clicking on the yellow square.
In Level 2, you have to go the entire level without getting rid of the tutorial.
In Level 3, when you interact with the catapults to replenish them, you can use that opportunity to use the mouse to click on the "Continue" button and get rid of the tutorial. But then the Replenish menu is on your screen until you interact again.

** Version **
Build GRV3_27

** Screenshots **
<img width="1438" alt="image" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/bcd40880-02d2-4e9a-a743-16dcf3c647f9">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
issues is due to something wrong with the tutorial start stuff on scene open fixed issues by reruning the code in update if it hasn't already run
