### ISSUE TITLE
Level 1: You start with 20 clay buckets in your inventory

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#68]
** Describe the bug **
When you load into level 1, you start with 20 clay bucket items in your first inventory slot.

** Version **
Build GRV3_27

** Screenshots **
<img width="1912" alt="20 clay buckets" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/fcf6e333-b0c2-4437-8082-6252a85d43d4">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
need clarifing why this is an issues

**Comment by Xeleolon** [comment]
updated
