### ISSUE TITLE
Level 4: Rubble in final chamber show red particles

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#71]
** Describe the bug **
The pile of Rubble in the final chamber show red particles and the rock icon, but you need to repair it with a rock. Should be yellow particles.

** Version **
Build GRV3_27

** Screenshots **
![Red particles](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/74fcedee-3ea2-44bf-a661-5fd9b48b9a43)

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
wrong type assigned as base refenernce in scripts
