### ISSUE TITLE
Level 3: Text box is showing level 1 message

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#73]
** Describe the bug **
In Level 3, the text box is showing the same message as in level 1. The bit about the courtyard.

** Version **
Build GRV3_29

** Screenshots **
<img width="1694" alt="level 3 text box" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/8fbfc595-5afa-493e-95e6-c1a3c27614c3">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
updated
