### ISSUE TITLE
Main Menu level title display correction

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#74]
** Description **
When selecting levels on the main menu, level titles should be displayed with a space before the number eg. "Level 1" and "Level 2" instead of the current "level1" and "Level2"

** Version **
MainV4.03

** OS **
Windows 10

**Comment by IgniusC** [comment]
This Issue only displays if the game window is active 
If Inactive:
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/1dd3d809-5d38-447a-944b-92d61934a460)

If Active:
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/f0cb2f9f-42b1-4667-a68a-3165cd81928a)

**Comment by Xeleolon** [comment]
this is due to level using level data name probably need to change it too level names so not an issues

**Comment by Xeleolon** [comment]
in active is different as it temporal text

**Comment by Xeleolon** [comment]
i fixed it
