### ISSUE TITLE
Dialogue Box need to play after tutorial

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#76]
** Description **
The Dialogue Box for the Dungeon Master is under the opacity filter for the tutorial on Level1 so it isn't easily noticeable and as it auto-plays players are liable to completely miss it before it disappears  

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/5e75caaf-5cd5-4c82-86dc-6ca59860ff6c)

** Version **
MainV4.03

** OS **
Windows 10

**Comment by Xeleolon** [comment]
Incorrect identified issues dialogue need to wait intill tutorial is over before playing

**Comment by DefinitelyACat** [comment]
Both Dialogue boxes and the "Press 1 to" tutorial bits have been removed from the game. Now, there is the simpler Level-specific scroll that instructs you on what needs to be done and can't be messed up timing-wise, as it is always present at the start of the level.
