### ISSUE TITLE
Dialogue text quoted incorrectly

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#77]
** Description **
Text within the Dialogue Box on Level1 incorrectly Quoted. Each text box requires its own start and end quotations instead of starting on the first box and ending on the second box.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/b18cb769-731d-4b7f-bd99-70b3d353ba81)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/f852d4c1-bcbc-4387-9e96-5d7551b4cb2d)

** Version **
MainV4.03

** OS **
Windows 10

**Comment by IgniusC** [comment]
Quotations corrected.

**Comment by Xeleolon** [comment]
No quation is needed at all

**Comment by Xeleolon** [comment]
removed quations
