### ISSUE TITLE
Repair tool unavailable in first level

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#79]
** Description **
After loading into the first level and completing the tutorial prompts you equip the destroy tool instead of the repair tool. This immediately locks the game as you can not repair anything to be capable of proceeding. Using the scroll wheel also does not allow you to access the repair tool either.

You also have an empty inventory so even if you had access to the repair tool you would also be unable to proceed.
** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/6c8e2b75-b1fa-4071-941e-08ed8e5b1ab0)

** Version **
MainV4.09

** OS **
Windows 10

**Comment by Xeleolon** [comment]
Fixed inventory beating levelmanger in getting level data called inventory start from level manager
