### ISSUE TITLE
No friction on "FloorPillarStraight" on Level 1 

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#80]
** Description **
In level 1 the "FloorPillarStraight" object (shown below) has no friction. The player will slide in the directed they were moving if they walk/jump on any of them. Direction can be changed while sliding but you you don't come to a stop until you have fallen onto the standard floor. You can also not jump while sliding

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/9507ad6c-949d-43b9-b044-ac73b133d22c)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by Xeleolon** [comment]
floor pillar need asigned floor tag

**Comment by Xeleolon** [comment]
fixed as 4.17
