### ISSUE TITLE
Various object clipping in level 1

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#84]
** Description **
Pretty much as title describes. There are various places in the level where objects are on the same plane and both textures are fighting to be displayed (as shown in screenshots).
This can be found:
In the Supply Room
Adjacent to most "FloorPillarStraight" objects
In the corner of the room in line with the exit gate.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/f45a0e50-c9d0-403a-a5dc-d3b96c747200)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/414b33dd-2327-48c4-833b-984f449ad328)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/0898d5e7-1473-42a4-b714-e4f38b741cef)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/b19278d1-c7fb-4827-840d-4832466d979f)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by IgniusC** [comment]
Also found on walls adjacent the Large Arch in the centre of the room as shown below.
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/befa6084-14cd-41e8-bcbb-6b384e4ca723)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/20f37b77-3dde-4907-8372-c63bf65eb903)

**Comment by Xeleolon** [comment]
angle floor were fixed merge broken them, just need to swap them prefab angled ones

**Comment by Xeleolon** [comment]
Fixed as version
