### ISSUE TITLE
Bookshelf in Level 1 needs new broken variant

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#85]
** Description **
In Level 1 the Bookshelf adjacent to the Exit gate has yet to be replaced with a broken variant. It is the only object from our PGF build that has not been replaced with a full textured broken variant. We need to ensure it is made consistent with the rest of the game.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/69df21bd-e7f7-4ba7-97b9-01474a44f881)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by Xeleolon** [comment]
completed
