### ISSUE TITLE
Repairing Broken wall does not fix wall on Level 1 

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#87]
** Description **
In level1 the player learns how to use the repair tool. However, in the case of the broken wall, when you "repair" it all that happens is the rubble disappears and the broken texture of the wall adjacent to the rubble remains the same. Effectively the player has added more rubble to the pile and it has suddenly disappeared into the shadow realm. Clarity needs to be created so the player recognises they have indeed repaired the wall and not just destroyed the rubble.

** Screenshot **
Before and After "Repair"
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/06a78a72-4a38-4667-ac11-fcce09400f5b)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/2b1e93d7-23f6-408a-92bd-9d6559b3327e)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by Xeleolon** [comment]
Fixed v4.17
