### ISSUE TITLE
Camera Clipping through arch

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#88]
** Description **
The player camera seems to be able to clip and see through all Arch models on Level 1. First recognised on the Supply Room Arch and replicated on both the Large and Exit Arches

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/251a75d2-d151-4108-91d1-0af1ff03b4ee)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/e4358a62-059b-433b-ad7b-9ca23fec90e3)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/f6875ce7-c1cc-4f75-b0c0-60582276c685)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/243f32a9-e313-4f7b-88bd-f524cbb30bcc)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by Xeleolon** [comment]
Fixed
