### ISSUE TITLE
Level 2 entrance gate

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#89]
** Description **
When you start Level 2 you can open the gate behind you. This is redundant and I have witnessed players be confused after doing so. We should eliminate this possibility.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/de4ed0ae-ecbc-4592-85f0-772d7f8f01a3)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/c9ca332e-b82c-4dbd-a7c9-a08bb9085959)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by Xeleolon** [comment]
give the door a key or the master key it cause the door to be deadlocked

**Comment by Xeleolon** [comment]
door given master key, as of version 4.17 and assigned it message 5
