### ISSUE TITLE
Player Camera Clipping through Fire place Level 2 

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#90]
** Description **
If the player attempts to run into the fireplace on Level 2 the camera will clip into the frame and enable them to see outside the level. I don't think we should stop the players from throwing themselves into the fireplace but we should address this issue.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/b191ffaf-23f4-402d-8a73-3cb182ba1e46)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/746ee5d5-c306-497c-94a4-2bd9c70d6aea)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by Xeleolon** [comment]
fixed increased fireplace hieght and added a damage player if they stay in the fire to get the player out of the fireplace
