### ISSUE TITLE
Inventory key rotated

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#93]
** Description **
As shown below the key and counter are rotated 90 degrees anti-clockwise.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/f6ebf2ef-ea7c-4311-85b8-242dc0fa4fb1)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by Xeleolon** [comment]
Fixed as of 4.17 need to have updated the prefab
