### ISSUE TITLE
Level 2 Door looks like it required repairing

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#94]
** Description **
At the start of level 2 at the bottom of the staircase in front of the player is a broken door. Haven just finished the tutorial level for repairing, I believe the players' natural instinct will be to attempt to repair this door not destroy it. I think it would be best if we replace this with a form of wooden barrier. By destroying this barrier you could also collect the wood required to repair the wooden staircase. This would work to connect the idea of destroying objects to collect materials necessary in later levels.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/831f2d7e-ee8f-40e2-9a49-63d07a4fcbb1)
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/179265fd-1bfd-4052-b89f-45624d91727b)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by Xeleolon** [comment]
incorrect collecting wood from the door would make collecting material not make sense as the player won't realize they need to collect some the point of havening to click on the floor first give the player a second lesson in repairing but also makes them consider using the destory to collect item

**Comment by DefinitelyACat** [comment]
This issue has been closed, as the door is the second thing available within the level to interact with and is posing as an obstacle that the player must "get rid of", so the hammer should be the thing they go for. If they don't it's a small mess-up on their part that serves the purpose of getting them to understand that not all things that look broken require fixing, and might instead need to be removed entirely. Such an instance shows up in the Potion level, later on.
