### ISSUE TITLE
Tutorial required to explain token

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#96]
** Description **
Currently there is no explanation or for of que set up for the player to understand what this token means. I think its great that we have it and it will be really useful but it requires adequate explanation for the player to figure out what it means.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/20952b04-2373-4bec-a483-10afb256f545)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by DefinitelyACat** [comment]
Tokens have now been mentioned in the presskit document that Riley (IgniusC) authored, under the FAQ section. Otherwise, this has been deemed something players should catch on to themselves.
