### ISSUE TITLE
Level3 Tutorial text

### ISSUE THREAD

**Issue by IgniusC** [Xeleolon/GremlinRestoration_Game#98]
** Description **
The tutorial text for Level 3 insufficiently explain the mechanic. Drag and drop does not make sense to all players. As with level 1 and 2 we should prevent progression until the player has completed a task to prove they understand the mechanic within this tutorial screen.

** Screenshot **
![image](https://github.com/Xeleolon/GremlinRestoration_Game/assets/127725061/1a1fc34f-0959-4a50-b2eb-f8f5cc1b06ed)

** Version **
MainV4.03 / IssueTracking Branch

** OS **
Windows 10

**Comment by Xeleolon** [comment]
removed tutorial entirely
