### ISSUE TITLE
All Levels: Repair tool is the blue hammer, Destroy tool is yellow wand

### ISSUE THREAD

**Issue by DefinitelyACat** [Xeleolon/GremlinRestoration_Game#99]
** Describe the bug **
In the first level, the only tool available to you is the "Repair Tool", but the model for it is the blue hammer that used to be for replenishing.
When you get introduced to the "Destroy Tool" in level 2, the model for it is the yellow staff that is meant for repairing.
In all later levels, these two stay as the two tools that have models available. The third setting of tools (Holding nothing) is still nothing.

** Version **
mainV4.17

** Screenshots **
Tool 1 is blue:
<img width="1100" alt="Tool 1 is replenish hammer" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/54a0f5c2-a411-448a-9d37-bb43c4986130">

Tool 2 is yellow:
<img width="1099" alt="Tool 2 is repair tool" src="https://github.com/Xeleolon/GremlinRestoration_Game/assets/127724850/0e534876-b934-4f24-bf66-8a85fdf7029e">

** Desktop System **
Windows 10

**Comment by Xeleolon** [comment]
put the wrong tools in when moving over from player movement to interact control now fixed
